Repository oscarine/oscarine-react-frontend, pull requests merged in 2021-06, with the labels that each got.

#64 chore: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#65 chore: Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#39 fix: Add cleanup in useEffecct & store latitude and longitude in localStorage
  src/components/Home/Home.js
  src/const/httpStatus.js
  src/const/navigatorErrorCode.js
  src/settings/config.js
  src/utils/storage.js
Labels: fix

#66 feat: Fetch items-list for user from server
  package.json
  src/App.js
  src/UI/ErrorModal.js
  src/UI/__tests__/ErrorModal.test.js
  src/components/Cart/Cart.js
  src/components/Home/Home.js
  src/components/Home/Shop.js
  src/components/ShopView/ItemCategory.js
  src/components/ShopView/ShopHeader.js
  src/components/ShopView/ShopItem.js
  src/components/ShopView/ShopSearch.js
  src/components/ShopView/ShopView.js
  src/components/ShopView/__tests__/ShopView.test.js
  src/utils/storage.js
Labels: feature
