Repository oscarine/oscarine-react-frontend, pull requests merged in 2021-05, with the labels that each got.

#2 feat: Add login signup front-end
  package.json
  src/App.js
  src/components/auth/Login.js
  src/components/auth/SignUp.js
  src/index.css
  yarn.lock
Labels: feature

#3 feat: Setup heroicons
  .vscode/settings.json
  package.json
  src/components/auth/Login.js
  yarn.lock
Labels: feature

#5 chore: Add dependabot config file
  .github/dependabot.yml
Labels: chore

#9 chore: Configure standardjs for local development
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  yarn.lock
Labels: chore

#13 feat: Add Shop Search & Layouts components
  src/App.js
  src/components/Home/Home.js
  src/components/Home/Search.js
  src/components/Home/Shop.js
  src/components/Layouts/BottomNav.js
  src/components/Layouts/Header.js
  src/components/auth/Login.js
  src/components/auth/SignUp.js
  src/index.css
  tailwind.config.js
Labels: feature

#15 feat: Add ShopView component
  package.json
  src/App.js
  src/components/Home/Home.js
  src/components/Home/Search.js
  src/components/Home/Shop.js
  src/components/Layouts/Header.js
  src/components/ShopView/ItemCategory.js
  src/components/ShopView/ShopHeader.js
  src/components/ShopView/ShopItem.js
  src/components/ShopView/ShopSearch.js
  src/components/ShopView/ShopView.js
  src/components/auth/Login.js
  src/components/auth/SignUp.js
Labels: feature

#17 fix: Improve BottomNav style and replace Link with NavLink in Header and BottomNav
  src/components/Layouts/BottomNav.js
  src/components/Layouts/Header.js
Labels: fix

#16 feat: Add ShopSearch component on large screen
  src/App.js
  src/components/ShopView/ShopSearch.js
  src/components/ShopView/ShopView.js
Labels: feature

#18 feat: Add login form validation and tests
  .deepsource.toml
  .github/workflows/test.yml
  .vscode/settings.json
  package.json
  src/App.test.js
  src/UI/Aux.js
  src/UI/FormikFormComponents/TextInput.js
  src/UI/__tests__/Aux.test.js
  src/components/auth/Login.js
  src/components/auth/__tests__/Login.test.js
  yarn.lock
Labels: feature

#27 chore: Add netlify and lighthouse dev dependency
  README.md
  netlify.toml
  package.json
  yarn.lock
Labels: chore

#26 feat: Add Cart component
  src/App.js
  src/components/Cart/Bill.js
  src/components/Cart/Cart.js
  src/components/Layouts/BottomNav.js
  src/components/Layouts/Header.js
  src/components/ShopView/ShopHeader.js
  src/components/ShopView/ShopItem.js
  src/components/ShopView/ShopView.js
  src/index.css
Labels: feature

#29 fix: Add reducer in Home and remove global reducer.js and StateProvider.js
  src/App.js
  src/App.test.js
  src/StateProvider.js
  src/components/Home/Home.js
  src/components/Home/reducer.js
  src/index.js
Labels: fix

#32 feat: Add loading UI in Home
  src/components/Home/Home.js
  src/components/Home/Shop.js
Labels: feature

#33 feat: Login using axios
  .gitignore
  src/UI/ThreeBounceLoader.js
  src/components/auth/Login.js
  src/endpoints.js
  src/index.js
  src/store/auth-context.js
  tailwind.config.js
Labels: feature

#34 fix: Add error and loading in home reducer
  src/components/Home/Home.js
  src/components/Home/reducer.js
Labels: fix

#36 feat: Add ErrorModal component
  src/UI/ErrorModal.js
  src/assets/images/sad-emoji.png
  src/components/Home/Home.js
  src/components/Home/Shop.js
Labels: feature
